# Generated by Django 5.1.5 on 2025-06-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/'),
        ),
    ]
