# Generated by Django 5.1.5 on 2025-06-27 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auctions.auctionitem'),
        ),
    ]
