# Generated by Django 5.2.3 on 2025-06-28 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 29, 12, 52, 53, 709930, tzinfo=datetime.timezone.utc)),
        ),
    ]
